name: Автоматический деплой сайта при удачном прохождении тестов и сборке

env:
  NODE_VERSION: '12.x'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm test
          npm run build
      
      - name: deploy
        run: |
          sudo apt-get install lftp
          lftp -h
